# A descriptive name for your workflow
name: Build and Push Docker Image to Docker Hub

# This section controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow is made up of one or more jobs
jobs:
  # This workflow contains a single job called "build-and-push"
  build-and-push:
    # This is the crucial line that tells the job to use your server
    runs-on: self-hosted

    # Steps represent the sequence of tasks for the job
    steps:
      # Step 1: Checks-out your repository code so the runner can use it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Logs in to Docker Hub using the secrets you configured
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Builds the Docker image from your Dockerfile and pushes it to your Docker Hub account
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # IMPORTANT: Update the line below with your Docker Hub username and desired image name.
          tags: sjpgh/ollama-comfyui-image:latest
